language: python
python:
    - "2.7"
addons:
  apt:
    packages:
      - swig
env:
    matrix:
        - TOX_ENV=py27-dj15
        - TOX_ENV=py27-dj16
        - TOX_ENV=py27-dj17
        - TOX_ENV=py27-dj18
install:
   - pip install tox
script: tox
