sudo: true
language: python
python:
    - "2.7"
addons:
  apt:
    packages:
      - swig

matrix:
  include:
    - python: 3.5
      env:
      - TOXENV=py35-dj15
      - TOXENV=py35-dj16
      - TOXENV=py35-dj17
      - TOXENV=py35-dj18
      - TOXENV=py35-dj19
    - python: 2.7
      env:
      - TOXENV=py27-dj15
      - TOXENV=py27-dj16
      - TOXENV=py27-dj17
      - TOXENV=py27-dj18
      - TOXENV=py27-dj19
install:
    - pip install tox
script: tox
